### PR TITLE
Fail gracefully createNativeCtxTexture in WebGlCoreCtxTexture load

### PR DESCRIPTION
**Pull request by CosmaVergari**
- Add try/catch block in WebGlCoreCtxTexture `load` method to manage the error thrown by `createNativeCtxTexture`
- Set the texture state to failed on error thrown

### CODE REVIEW

**Comment by wouterlucas** [comment]
Try / Catch statements are notoriously dangerous for their performance impact, as essentially you're copying the stack just in case _something_ might happen. 

What is the error exactly and isn't this handled in the `catch` already?

**Comment by CosmaVergari** [comment]
I just made a change to address your point. The idea is to manage the error raised by `createNativeCtxTexture` [here](https://github.com/lightning-js/renderer/blob/dd9461f55ae7a2946141af934c84d88335c937bb/src/core/renderers/webgl/WebGlCoreCtxTexture.ts#L248)

**Comment by CosmaVergari** [comment]
Thank you for the suggestion, I converted the raised error to a `null` return. The performance gain seems significant indeed

**Comment by wouterlucas** [comment]
Thanks for your contribution!

**Review by wouterlucas — APPROVED** [review]

**Pull request merged**
