### PR TITLE
Text Autosize Behavior

### LINKED ISSUE #28: Add w/h to textnode

### PR DESCRIPTION
**Pull request by frank-weindel**
Depending on the set contain mode, after the text 'loaded' event is emitted,
the text node may have either its width and height updated
to match the rendered size of the text.

When contain mode is 'none', both the width and height
properties are updated.

When contain mode is 'width', only the height property is updated.

When contain mode is 'both', neither property is updated.

Resolves #28

### CODE REVIEW

**Review by chiefcll — APPROVED** [review]
LGTM

**Comment by pecoram** [comment]
Is it correct that letters such as "g" are cut off in snapshots ?
Granted that I haven't done any tests, with this modification does the alignCenter still work?

**Comment by frank-weindel** [comment]
The descenders being cut of from the reported text height is existing behavior. I've got a proposal to fix that and make the reporting more consistent:
- #170 

As for #183, are you 100% sure? I wouldn't expect much of any behavior change when contain is set to "both". I will take your word for it though.

**Comment by scailbc** [comment]
Hello, I'm seeing an error on word wrap that could be related.
Screenshot 2024-03-15 at 17 23 19
Screenshot 2024-03-15 at 17 23 42
As you can see a word with a single character is not wrapped correctly, while with 2 characters works fine.

Here is the code:
```js
<View x={400} y={500} width={100} height={100} color={0xff0000ff}>
    <Text fontSize={20} width={100} contain="width">
        Lorem ips e dolor
    </Text>
</View>
```

I'm using the renderer v0.7.5. Can you give it a check?

**Review by wouterlucas — APPROVED** [review]
LGTM

**Pull request merged**
